# Generated by Django 4.2.4 on 2023-08-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post-images/default.png', null=True, upload_to='post-images'),
        ),
    ]
