# Generated by Django 4.2.4 on 2023-08-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emale',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
