# Generated by Django 4.2.4 on 2023-08-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_emale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='emale',
            new_name='email',
        ),
    ]
